forecast_horizon: 5
har_windows:
  long: 21
  medium: 5
  short: 1
implied_path: data/iv_implied.parquet
implied_z: true
model_path: models/best_model.pkl
new_implied_path: data/new_implied.parquet
new_realized_path: data/new_realized.parquet
option_chain_path: data/option_chain.parquet
output_ledger_path: results/ledger.parquet
price_path: data/underlying_prices.parquet
ranking_threshold: 0.9
realized_path: data/iv_data.parquet
rf_params:
  max_depth: 5
  n_estimators: 100
signal_z: true
train_test_gap_days: 21
train_test_split_ratio: 0.7
